version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
        ports:
            - 8000:80
        container_name: ${CONTAINER_PREFIX}_nginx
        depends_on:
            - app
    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www/
        container_name: ${CONTAINER_PREFIX}_app
        depends_on:
            - db
    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3306:3306"
        container_name: ${CONTAINER_PREFIX}_db
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        restart: always
        depends_on:
            - db
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
        ports:
            - "8080:80"
        container_name: ${CONTAINER_PREFIX}_phpmyadmin
volumes:
    mysql_data:
